# https://docs.spacelift.io/concepts/configuration/runtime-configuration

version: "1"

stack_defaults:
  before_init:
    - spacelift-write-vars
    - spacelift-tf-workspace

  before_plan: []
      
  before_apply: []

  environment:
    AWS_SDK_LOAD_CONFIG: true
    AWS_CONFIG_FILE: /etc/aws-config/aws-config-cicd
    AWS_PROFILE: kin-gbl-identity
    ATMOS_BASE_PATH: /mnt/workspace/source

stacks:
  # You can override things like the tf version for specific stacks here.
  # This is very handy for testing tf upgrades without affecting normal deploys.
  # eg:
  # ue2-devplatform-maestro:
  #   terraform_version: "1.5"

  frastructure:
    before_init: []
    before_plan: []
    before_apply: []

